services:
  productcatalog.api:
    image: ${DOCKER_REGISTRY-}productcatalogapi
    container_name: ProductCatalog.Api
    build:
      context: .
      dockerfile: ProductCatalog.Api/Dockerfile
    depends_on:
      - productcatalog.db
      - productcatalog.seq

  productcatalog.db:
    image: postgres:latest
    container_name: ProductCatalog.Db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=productcatalog
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5400:5432

  productcatalog.idp:
    image: quay.io/keycloak/keycloak:latest
    container_name: ProductCatalog.Identity
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./.files/ProductCatalog-realm.json:/opt/keycloak/data/import/ProductCatalog-realm.json:ro
      - keycloak_data:/opt/keycloak/data
    ports:
      - "18080:8080"
  
  productcatalog.seq:
    image: datalust/seq:latest
    container_name: ProductCatalog.Seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=admin
    ports:
      - 5341:5341
      - 8081:80

volumes:
  keycloak_data: