services:
  productcatalog.api:
    image: ${DOCKER_REGISTRY-}productcatalogapi
    container_name: ProductCatalog.Api
    build:
      context: .
      dockerfile: ProductCatalog.Api/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - productcatalog.db
      - productcatalog.seq

  productcatalog.db:
    image: postgres:latest
    container_name: ProductCatalog.Db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=productcatalog
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
      - ./.containers/init:/docker-entrypoint-initdb.d
    ports:
      - 5400:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  productcatalog.idp:
    image: quay.io/keycloak/keycloak:latest
    container_name: ProductCatalog.Identity
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://productcatalog.db:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    volumes:
      - ./.files/ProductCatalog-realm.json:/opt/keycloak/data/import/ProductCatalog-realm.json:ro
    depends_on:
      productcatalog.db:
        condition: service_healthy
    ports:
      - "18080:8080"
  
  productcatalog.seq:
    image: datalust/seq:latest
    container_name: ProductCatalog.Seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=admin
    ports:
      - 5341:5341
      - 8081:80
   
  productcatalog.redis:
    image: redis:latest
    container_name: ProductCatalog.Redis
    restart: always
    ports:
      - '6830:6379'

